services:
  {{projectName}}-server:
    container_name: {{projectName}}-server
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile} 
      target: {{projectName}}-server
      args:
        - DOCKER_BUILDKIT=1
    ports:
      - "3020:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVER_HOST=http://host.docker.internal:3020
      - GIT_COMMIT_TIME=${GIT_COMMIT_TIME}
      - GIT_COMMIT_MESSAGE=${GIT_COMMIT_MESSAGE}

  {{projectName}}-h5:
    container_name: {{projectName}}-fe
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile} 
      target: {{projectName}}-fe
      args:
        - DOCKER_BUILDKIT=1
    ports:
      - "3033:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GIT_COMMIT_TIME=${GIT_COMMIT_TIME}
        - GIT_COMMIT_MESSAGE=${GIT_COMMIT_MESSAGE}
  {{projectName}}-manage:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile} 
      target: {{projectName}}-manage
      args:
        - DOCKER_BUILDKIT=1
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GIT_COMMIT_TIME=${GIT_COMMIT_TIME}
      - GIT_COMMIT_MESSAGE=${GIT_COMMIT_MESSAGE}

